services:
    top-courses-api:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                NODE_ENV: docker
                MONGO_DOCKER_URI: ${MONGO_DOCKER_URI}
                MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
                MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
                JWT_SECRET: ${JWT_SECRET}
                DOMAIN: ${DOMAIN}
                TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
                CHAT_ID: ${CHAT_ID}
                HH_TOKEN: ${HH_TOKEN}
        image: top-courses-api:latest
        container_name: top-courses-api
        restart: always
        ports:
            - 3000:3000
        volumes:
            - ./.env:/opt/app/.env
        environment:
            NODE_ENV: docker
            MONGO_DOCKER_URI: ${MONGO_DOCKER_URI}
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
            JWT_SECRET: ${JWT_SECRET}
            DOMAIN: ${DOMAIN}
            TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
            CHAT_ID: ${CHAT_ID}
            HH_TOKEN: ${HH_TOKEN}
        networks:
            - top-courses-network

networks:
    top-courses-network:
        external: true
